apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-webservice
spec:
  components:
    - name: simple-hello-world-server
      type: webservice
      properties:
        image: somefive/hello-world:kubevela
        port: 80
      traits:
        - type: scaler
          properties:
            replicas: 3
        - type: rollout
          properties:
            rolloutBatches:
              - replicas: 1
              - replicas: 2
        - type: ingress
          properties:
            domain: testsvc.example.com
            http:
              "/": 80