apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: simple-hello-world-server
spec:
  components:
    - name: simple-hello-world-server
      type: webservice
      properties:
        image: somefive/hello-world:kubevela-demo
        imagePullPolicy: Always
        port: 80
      traits:
        - type: scaler
          properties:
            replicas: 5
        - type: rollout
          properties:
            rolloutBatches:
              - replicas: 1
              - replicas: 1
              - replicas: 3
        - "type": labels
          "properties":
            "jenkins-build-commit": GIT_COMMIT
        - type: ingress
          properties:
            domain: http://hello-world.cf7c0ed25b151437ebe1ef58efc29bca4.us-west-1.alicontainer.com/
            http:
              "/": 80